spring.application.name=controle-funcionario
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/funcionarios
spring.datasource.username=root
spring.datasource.password=root
